---  
  training:    
    dataloader:
      batch_size: 16
      num_workers: 4
      shuffle: true
      pin_memory: false
    select_frame: 10   
    num_epochs: 300
    learning_rate: 0.002175482870728186
    lr_patience: 10
    log_interval: 1
    save_checkpoint: false
    save_tensorboard: false
    deterministic: false
    save_model_path: "/usr/local/data01/rohitram/sbu-snapshots/"
    save_tensorboard_dir: "/usr/local/data01/rohitram/sbu-snapshots/"
    pytorch_seed: 0
    folds: [0]
    num_runs: 1
    model: "model4"

  model1: 
    resize: 224       
    CNN_embed_dim: 256
    num_classes: 8 
    frameLSTM:
      hidden_size: 256
      winit: "default"
      forget_gate_bias: "default"
    eventLSTM:  
      hidden_size: 256 
      winit: "default"
      forget_gate_bias: "default"
    
  model2:
    pose_dim: 30
    pose_coord: 2 # 2=>(x,y), 3=>(x,y,z)
    num_classes: 8 
    eventLSTM:  
      hidden_size: 256 
      winit: "default"
      forget_gate_bias: "default"

  model3:
    pose_dim: 30
    pose_coord: 2 # 2=>(x,y), 3=>(x,y,z)
    num_classes: 8 
    eventLSTM:  
      hidden_size: 256 
      winit: "default"
      forget_gate_bias: "default"
    attention_type: 1

  model4:
    resize: 224       
    CNN_embed_dim: 256
    num_classes: 8 
    pose_dim: 30
    pose_coord: 2 # 2=>(x,y), 3=>(x,y,z)
    frameLSTM:
      hidden_size: 242
      winit: "default"
      forget_gate_bias: "default"
    eventLSTM:  
      hidden_size: 233
      winit: "default"
      forget_gate_bias: "default"
    attention_params:
      hidden_size: 306
      bias: true
