dataset_name: "Hockey"
dataset_path: "/home/fay/Desktop/Key-Actor-Detection/hockey_dataset"

num_nodes: 1 # number of nodes
gpus: [0] # list of gpu indices on each node

training:    
  train_dataloader:
    batch_size: 32
    num_workers: 4
    shuffle: True
  val_dataloader:
    batch_size: 32
    num_workers: 4
    shuffle: false
  test_dataloader:
    batch_size: 32
    num_workers: 4
    shuffle: false
  num_frames: 64  
  max_players: 8
  num_epochs: 100
  learning_rate: 0.0001
  wd : 0
  patience : 100
  save_dir: "/home/fay/Desktop/Key-Actor-Detection/work_dir/model3axwd" #null for no saving
  folds: [1] # choose from 1,2,3,4,5
  num_runs: 1 # each fold will be run these many times
  model: "model2"

deterministic:
  set: true
  seed: 50

model1: 
  resize: 224       
  CNN_embed_dim: 256
  num_classes: 3
  frameLSTM:
    hidden_size: 512
    winit: "default"
    forget_gate_bias: "default"
  eventLSTM:  
    hidden_size: 512
    winit: "default"
    forget_gate_bias: "default"
  
model2:
  num_classes: 3
  num_keypoints: 16
  coords_per_keypoint: 2 # always 2
  eventLSTM:  
    hidden_size: 512
    winit: "default"
    forget_gate_bias: "default"

model3:
  num_classes: 3
  num_keypoints: 16
  coords_per_keypoint: 2
  eventLSTM:  
    hidden_size: 512
    winit: "default"
    forget_gate_bias: "default"
  attention_type: 2
  attention_params:
    hidden_size: 512
    bias: true

model4:
  resize: 224       
  CNN_embed_dim: 256
  num_classes: 3
  num_keypoints: 16
  coords_per_keypoint: 2
  frameLSTM:
    hidden_size: 256
    winit: "default"
    forget_gate_bias: "default"
  eventLSTM:  
    hidden_size: 256
    winit: "default"
    forget_gate_bias: "default"
  attention_type: 3
  attention_params:
    hidden_size: 256
    bias: true