dataset_name: "Hockey"
dataset_path: "/usr/local/data01/rohitram/hockey_dataset"

num_nodes: 1 # number of nodes
gpus: [0] # list of gpu indices on each node
  
training:    
  train_dataloader:
    batch_size: 16
    num_workers: 4
    shuffle: true
  val_dataloader:
    batch_size: 16
    num_workers: 4
    shuffle: false
  num_frames: 64  
  max_players: 15
  num_epochs: 50
  learning_rate: 0.002
  save_dir: "./mlruns" #null for no saving
  folds: [1] # choose from 1,2,3,4,5
  num_runs: 1 # each fold will be run these many times
  model: "model3"

deterministic:
  set: true
  seed: 50

model1: 
  resize: 224       
  CNN_embed_dim: 256
  num_classes: 3
  frameLSTM:
    hidden_size: 256
    winit: "default"
    forget_gate_bias: "default"
  eventLSTM:  
    hidden_size: 256 
    winit: "default"
    forget_gate_bias: "default"
  
model2:
  num_classes: 3
  num_keypoints: 20
  coords_per_keypoint: 2 # always 2
  eventLSTM:  
    hidden_size: 256 
    winit: "default"
    forget_gate_bias: "default"

model3:
  num_classes: 3
  num_keypoints: 20 
  coords_per_keypoint: 2
  eventLSTM:  
    hidden_size: 128 
    winit: "default"
    forget_gate_bias: "default"
  attention_type: 2

model4:
  resize: 224       
  CNN_embed_dim: 256
  num_classes: 3
  num_keypoints: 20
  coords_per_keypoint: 2
  frameLSTM:
    hidden_size: 256
    winit: "default"
    forget_gate_bias: "default"
  eventLSTM:  
    hidden_size: 256
    winit: "default"
    forget_gate_bias: "default"
  attention_params:
    hidden_size: 256
    bias: true